# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-03 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='startDate',
            new_name='Date',
        ),
    ]
