# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200903_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('humidity', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
